/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedBrandRouteImport } from './routes/_authenticated/brand'
import { Route as AuthenticatedListingsIndexRouteImport } from './routes/_authenticated/listings.index'
import { Route as AuthenticatedListingsIdRouteImport } from './routes/_authenticated/listings.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandRoute = AuthenticatedBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsIndexRoute =
  AuthenticatedListingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedListingsRoute,
  } as any)
const AuthenticatedListingsIdRoute = AuthenticatedListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/images': typeof AuthenticatedImagesRoute
  '/listings': typeof AuthenticatedListingsRouteWithChildren
  '/market': typeof AuthenticatedMarketRoute
  '/products': typeof AuthenticatedProductsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/listings/': typeof AuthenticatedListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/images': typeof AuthenticatedImagesRoute
  '/market': typeof AuthenticatedMarketRoute
  '/products': typeof AuthenticatedProductsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/listings/$id': typeof AuthenticatedListingsIdRoute
  '/listings': typeof AuthenticatedListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/brand': typeof AuthenticatedBrandRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRouteWithChildren
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/listings/$id': typeof AuthenticatedListingsIdRoute
  '/_authenticated/listings/': typeof AuthenticatedListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brand'
    | '/competitors'
    | '/dashboard'
    | '/generate'
    | '/images'
    | '/listings'
    | '/market'
    | '/products'
    | '/seo'
    | '/settings'
    | '/listings/$id'
    | '/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brand'
    | '/competitors'
    | '/dashboard'
    | '/generate'
    | '/images'
    | '/market'
    | '/products'
    | '/seo'
    | '/settings'
    | '/listings/$id'
    | '/listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/brand'
    | '/_authenticated/competitors'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/images'
    | '/_authenticated/listings'
    | '/_authenticated/market'
    | '/_authenticated/products'
    | '/_authenticated/seo'
    | '/_authenticated/settings'
    | '/_authenticated/listings/$id'
    | '/_authenticated/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand': {
      id: '/_authenticated/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/': {
      id: '/_authenticated/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof AuthenticatedListingsIndexRouteImport
      parentRoute: typeof AuthenticatedListingsRoute
    }
    '/_authenticated/listings/$id': {
      id: '/_authenticated/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AuthenticatedListingsIdRouteImport
      parentRoute: typeof AuthenticatedListingsRoute
    }
  }
}

interface AuthenticatedListingsRouteChildren {
  AuthenticatedListingsIdRoute: typeof AuthenticatedListingsIdRoute
  AuthenticatedListingsIndexRoute: typeof AuthenticatedListingsIndexRoute
}

const AuthenticatedListingsRouteChildren: AuthenticatedListingsRouteChildren = {
  AuthenticatedListingsIdRoute: AuthenticatedListingsIdRoute,
  AuthenticatedListingsIndexRoute: AuthenticatedListingsIndexRoute,
}

const AuthenticatedListingsRouteWithChildren =
  AuthenticatedListingsRoute._addFileChildren(
    AuthenticatedListingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandRoute: typeof AuthenticatedBrandRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRouteWithChildren
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandRoute: AuthenticatedBrandRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRouteWithChildren,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
